name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.8'

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc install 0.8.16
        run: solc-select install 0.8.16

      - name: Solc use 0.8.16
        run: solc-select use 0.8.16

      - name: Verify solc version used
        run: solc --version

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: test foundry version
        run: foundryup -v nightly-8bbde620ab39246f3c89700a19dfe6f347e99f4f

      - name: Run tests
        run: forge test -vvvv
